repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [ "--maxkb=1492" ]
      - id: no-commit-to-branch
        args: [ '--branch', 'main' ]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    -   id: add-trailing-comma

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/crate-ci/typos
    rev: v1.14.3
    hooks:
      - id: typos
        exclude: >
          (?x)^(
              .*\.css|
              .*\.js|
              \.tox|
          )$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.260
    hooks:
      - id: ruff


  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [ "--config", "pyproject.toml" ]


  - repo: https://github.com/python-poetry/poetry
    rev: 1.4.0
    hooks:
      - id: poetry-check

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.1
    hooks:
      - id: docformatter

  - repo: https://github.com/nrbnlulu/qt-hooks
    rev: v0.1.5
    hooks:
      - id: qml-format

exclude: >
          (?x)^(
              .*\.jinja.py|
          )$
